# SITE CONFIGURATION
title: Natalia Zuniga  # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Natalia Zuniga personal website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nzunigag.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nzunigag

# SEO PLUGIN
social:
  name: Natalia
  links:
    - https://www.linkedin.com/in/nzunigag/
    - https://github.com/nzunigag
    - https://www.instagram.com/nataliazunigag/

# THEME SETTINGS
navigation: # Navigation links
  # - {name: 'About', link: '/about'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'Teaching', link: '/teaching'}
  - {name: 'Activities', link: '/activities'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Data Scientist 

hero_img: /assets/img/main.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: nzuniga@utexas.edu # email for form submission

twitter_username: NataliaZunigaG # replace with your_twitter_username or comment to remove link from footer
github_username:  nzunigag # replace with your_github_username or comment to remove link from footer
instagram_username: nataliazunigag # replace with your_instagram_username or comment to remove link from footer
linkedin_username: nzunigag

# disqus:
  # shortname: nataliazuniga # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-KT7GZ24 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
